name: Enhanced Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
      FOOTBALL_DATA_API_URL: ${{ secrets.FOOTBALL_DATA_API_URL }}
      NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID: ${{ secrets.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID }}
      GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_SITE_VERIFICATION }}
      NEXT_PUBLIC_FEATURE_CLERK_AUTH: "true" # Assuming we want to test auth
      # Add other NEXT_PUBLIC_FEATURE_ flags here if you want to explicitly enable them for CI testing
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run ESLint
        run: npm run lint
      - name: Run Type Check
        run: npm run type-check
      - name: Run Jest Tests
        run: npm test
      - name: Run E2E Tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Install lsof
        run: sudo apt-get update && sudo apt-get install -y lsof
      - name: Build Project
        run: |
          npm run build
      - name: Start Built Project
        run: |
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
          FOOTBALL_DATA_API_KEY=${{ secrets.FOOTBALL_DATA_API_KEY }} \
          FOOTBALL_DATA_API_URL=${{ secrets.FOOTBALL_DATA_API_URL }} \
          NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID=${{ secrets.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID }} \
          GOOGLE_SITE_VERIFICATION=${{ secrets.GOOGLE_SITE_VERIFICATION }} \
          NEXT_PUBLIC_FEATURE_CLERK_AUTH=${{ secrets.NEXT_PUBLIC_FEATURE_CLERK_AUTH }} \
          npm run dev &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000 --timeout 120000 # Increased timeout to 2 minutes
      - name: Run Lighthouse Accessibility
        run: npm run lighthouse:accessibility
      - name: Stop Development Server
        run: kill $(lsof -t -i:3000) || true
